agendas/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.Selector.as_view(), name='agendas-selector'),
    path('studio-preferences/', views.StudioPreferences.as_view(), name='agendas-studio-preferences'),
    re_path(
        r'^(?P<cat_slug>[\w,-]+)/booking/(?P<pk>\d+)/popup/$',
        views.BookingPopupView.as_view(),
        name='agendas-booking-popup',
    ),
    re_path(r'^(?P<slug>[\w,-]+)/$', views.Agendas.as_view(), name='agendas-view'),
    re_path(
        r'^(?P<cat_slug>[\w,-]+)/new/$', views.CreateBookingView.as_view(), name='agendas-create-booking'
    ),
    re_path(r'^(?P<slug>[\w,-]+)/settings/$', views.AgendasSettingsView.as_view(), name='agendas-settings'),
    re_path(
        r'^(?P<cat_slug>[\w,-]+)/settings/disable-agenda/(?P<pk>\d+)/$',
        views.DisableAgendaLineView.as_view(),
        name='agendas-disable-line',
    ),
    re_path(
        r'^(?P<cat_slug>[\w,-]+)/settings/add-agenda/$',
        views.CreateAgendaLineView.as_view(),
        name='agendas-create-line',
    ),
]

agendas/models.py
import datetime

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from emissions.models import Absence, Diffusion
from nonstop.models import ScheduledDiffusion

from .app_settings import app_settings


class Category(models.Model):
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['label']

    label = models.CharField(_('Label'), max_length=50)
    slug = models.SlugField()
    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    last_update_timestamp = models.DateTimeField(auto_now=True, null=True)
    label_presets = models.TextField(_('Presets for labels'), blank=True, null=True)

    def __str__(self):
        return self.label

    def get_label_presets(self):
        return [x for x in (self.label_presets or '').split('\n') if x]


class Agenda(models.Model):
    class Meta:
        verbose_name = _('Agenda')
        verbose_name_plural = _('Agendas')
        ordering = ['category__label', 'category_order', 'label']

    label = models.CharField(_('Label'), max_length=50)
    slug = models.SlugField()
    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    last_update_timestamp = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    category_order = models.PositiveIntegerField(default=0)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.label


class Booking(models.Model):
    class Meta:
        verbose_name = _('Booking')
        verbose_name_plural = _('Bookings')

    start_datetime = models.DateTimeField(_('Date/time'))
    duration = models.IntegerField(_('Duration'))
    label = models.CharField(_('Label'), max_length=250)
    colour = models.CharField(_('Colour'), max_length=20, default='#eeeeee')
    comment = models.TextField(_('Comment'), blank=True)

    agenda = models.ForeignKey(Agenda, null=True, blank=False, on_delete=models.SET_NULL)
    diffusion = models.ForeignKey('emissions.Diffusion', null=True, blank=True, on_delete=models.CASCADE)
    schedule = models.ForeignKey('emissions.Schedule', null=True, blank=True, on_delete=models.CASCADE)

    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    last_update_timestamp = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.label

    def css_classes(self):
        return 'occupied'

    @property
    def emission(self):
        if self.diffusion:
            return self.diffusion.emission
        if self.schedule:
            return self.schedule.emission
        return None

    def create_secondary(self):
        if not self.emission:
            return
        try:
            pref = EmissionAgendaPreference.objects.get(emission=self.emission)
        except EmissionAgendaPreference.DoesNotExist:
            return
        if not pref.agenda:
            return
        booking, created = Booking.objects.get_or_create(
            start_datetime=self.start_datetime - datetime.timedelta(minutes=pref.pre_time or 0),
            duration=self.duration + (pref.pre_time or 0) + (pref.post_time or 0),
            label=self.label,
            comment=self.comment,
            diffusion=self.diffusion,
            schedule=self.schedule,
            agenda=pref.agenda,
        )

    def fg_colour(self):
        # luminance coefficients taken from section C-9 from
        # http://www.faqs.org/faqs/graphics/colorspace-faq/
        brightess = (
            int(self.colour[1:3], 16) * 0.212671
            + int(self.colour[3:5], 16) * 0.715160
            + int(self.colour[5:7], 16) * 0.072169
        )
        if brightess > 128:
            fg_colour = 'black'
        else:
            fg_colour = 'white'
        return fg_colour

    def end_datetime(self):
        return self.start_datetime + datetime.timedelta(minutes=self.duration)


class EmissionAgendaPreference(models.Model):
    emission = models.ForeignKey('emissions.Emission', on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, null=True, blank=False, on_delete=models.SET_NULL)
    pre_time = models.IntegerField(default=0)
    post_time = models.IntegerField(default=0)

    def __str__(self):
        return '%s - %s' % (self.emission, self.agenda)


@receiver(post_save, sender=Diffusion)
def save_diffusion(sender, instance, **kwargs):
    default_agenda = None
    if app_settings.DEFAULT_AGENDA_SLUG:
        default_agenda = Agenda.objects.get(slug=app_settings.DEFAULT_AGENDA_SLUG)

    bookings = Booking.objects.filter(diffusion=instance)
    if not bookings.exists():
        # remove bookings created on emission schedule
        for booking in Booking.objects.filter(start_datetime=instance.datetime, schedule__isnull=False):
            if booking.schedule.emission == instance.emission:
                booking.delete()

        booking, created = Booking.objects.get_or_create(
            diffusion=instance,
            defaults={
                'start_datetime': instance.datetime,
                'duration': instance.get_duration(),
                'label': str(instance.episode.emission),
                'agenda': default_agenda,
            },
        )
        booking.create_secondary()
    else:
        for booking in bookings:
            booking.start_datetime = instance.datetime
            booking.duration = instance.get_duration()
            booking.save()


@receiver(post_save, sender=Absence)
def save_absence(sender, instance, **kwargs):
    Booking.objects.filter(schedule__emission=instance.emission, start_datetime=instance.datetime).delete()


@receiver(post_save, sender=ScheduledDiffusion)
def save_scheduled_diffusion(sender, instance, **kwargs):
    # remove studio booking when a diffusion is programmed.
    if app_settings.DEFAULT_AGENDA_SLUG:
        default_agenda = Agenda.objects.get(slug=app_settings.DEFAULT_AGENDA_SLUG)
        Booking.objects.filter(diffusion=instance.diffusion).exclude(agenda=default_agenda).delete()

agendas/templates/agendas/agenda_form.html
{% extends "base.html" %}
{% load gadjo i18n %}

{% block appbar %}
  <h2>{% trans "New Agenda Line" %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|with_template }}
    <div class="buttons">
      <button class="submit-button">{% trans "Add" %}</button>
      <a class="cancel" href=".">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

agendas/templates/agendas/agendas.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{{ object }} | {% trans "Agendas" %} | {{ block.super }}{% endblock %}

{% block gadjo-js %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/panik-agendas.js"></script>
{% endblock %}

{% block css %}
  {{ block.super }}
  <link href="{{ STATIC_URL }}css/panik-agendas.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  {% if user_has_perm %}
    <a style="float: right" data-popup class="pk-button" href="settings/">{% trans "Settings" %}</a>
  {% endif %}
{% endblock %}

{% block appbar %}
  <h2><a href="./">Agendas - {{ object }}</a></h2>
  <span class="actions">
    <a class="date-nav" href="?date={{n_next_page_date|date:"Y-m-d"}}">&Gt;</a>
    <a class="date-nav" href="?date={{next_page_date|date:"Y-m-d"}}">&gt;</a>
    <a class="date-nav" href="?date={{prev_page_date|date:"Y-m-d"}}">&lt;</a>
    <a class="date-nav" href="?date={{p_prev_page_date|date:"Y-m-d"}}">&Lt;</a>
    <a style="display: none;" class="new" rel="popup" href="{% url 'agendas-create-booking' cat_slug=object.slug %}">Poser une réservation</a>
  </span>
{% endblock %}

{% block content %}

  <div class="section">
    <div>
      {% for day_info in day_infos %}
        <table class="occupancy {% if user_has_perm %}user-has-perm{% endif %}">
          <thead>
            <tr>
              <th>{{ day_info.day|date:"l j F"|lower }}</th>
              {% for hour in hours %}
                <td colspan="2">{{ hour }}</td>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for agenda_line in day_info.agenda_lines %}
              <tr data-agenda-pk="{{ agenda_line.agenda.id }}">
                <th>{{ agenda_line.agenda.label }}</th>
                {% for cell in agenda_line.cells %}
                  <td {% if not cell.blank %}title="{{ cell.start_datetime|date:"H:i" }} → {{ cell.end_datetime|date:"H:i" }} : {{ cell }}"{% endif %} colspan="{{ cell.width }}" {% if cell.colour %}style="background: {{cell.colour}}; color: {{cell.fg_colour}};"{% endif %} class="{{ cell.css_classes }}" {{cell.attributes}}
                  >{% if not cell.blank %}<a
                    {% if user_has_perm %}
                      href="{% url 'agendas-booking-popup' pk=cell.id cat_slug=object.slug %}" rel="popup"
                    {% else %}
                      href="#"
                    {% endif %}>{{ cell }}</a>{% endif %}</td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endfor %}
    </div>
  </div>

{% endblock %}

agendas/templates/agendas/booking_form.html
{% extends "base.html" %}
{% load gadjo i18n %}

{% block appbar %}
  {% if booking.id %}
    <h2>{% trans "Booking" %}</h2>
  {% else %}
    <h2>{% trans "New Booking" %}{% if agenda %} - {{ agenda }}{% endif %}</h2>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post" class="booking-form {% if booking.id %}edit-form{% endif %}">
    {% csrf_token %}
    {{ form|with_template }}
    <div class="buttons">
      <button class="submit-button">{% if booking.id %}{% trans "Save" %}{% else %}{% trans "Add" %}{% endif %}</button>
      {% if booking.id %}<button name="delete-button" value="delete" class="delete-button">{% trans "Delete" %}</button>{% endif %}
      <a class="cancel" href="..">{% trans "Cancel" %}</a>
    </div>

    <script>
      $('#colour-copy').val($('#id_colour').val());
      $('#colour-copy').on('change', function() { $('#id_colour').val($(this).val()); });
    </script>
  </form>
{% endblock %}

agendas/templates/agendas/booking_label.html
<div class="booking-label">
  {% include "django/forms/widgets/text.html" %}
  <input type="color" id="colour-copy">
</div>
{% if booking and booking.schedule %}
  → <a href="{% url 'emission-view' slug=booking.schedule.emission.slug %}">{{ booking.schedule.emission }}</a>
{% elif booking and booking.diffusion %}
  → <a href="{% url 'episode-view' emission_slug=booking.diffusion.emission.slug slug=booking.diffusion.episode.slug %}">{{ booking.diffusion.emission }}</a>
{% else %}
  {% with presets=category.get_label_presets %}
    {% if presets %}
      <div class="prelabels">
        {% for label in presets %}<button data-forloop-counter="{{ forloop.counter }}" type="button">{{ label }}</button> {% endfor %}
      </div>
      <script>
        $('.prelabels button').on('click', function() {
          $('input[name={{ widget.name }}]').val($(this).text());
          var counter = $(this).data('forloop-counter');
          var colours = Array('#8dd3c7', '#ffffb3', '#fb8072', '#80b1d3', '#fdb462');
          $('#colour-copy').val(colours[counter-1]).trigger('change');
        });
      </script>
    {% endif %}
  {% endwith %}
{% endif %}

agendas/templates/agendas/category_form.html
{% extends "base.html" %}
{% load gadjo i18n %}

{% block appbar %}
  <h2>{% trans "Agendas Settings" %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|with_template }}

    <ul class="objects-list single-links">
      {% for agenda in lines %}
        <li><a href="">{{ agenda }}</a>
          <a class="delete" href="{% url 'agendas-disable-line' cat_slug=object.slug pk=agenda.id %}">{% trans "disable" %}</a>
        </li>
      {% endfor %}
      <li><a data-popup href="{% url 'agendas-create-line' cat_slug=object.slug %}">+ {% trans "Add agenda line" %}</a></li>
    </ul>

    <div class="buttons">
      <button class="submit-button">{% trans "Save" %}</button>
      <a class="cancel" href="..">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

agendas/templates/agendas/category_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Agendas" %} | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>{% trans "Agendas" %}</h2>
{% endblock %}

{% block content %}

  <div class="section">
    <ul class="objects-list single-links">
      {% for category in object_list %}
        <li><a href="{% url 'agendas-view' slug=category.slug %}">{{ category }}</a></li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

agendas/templates/agendas/duration.html
<span class="duration">
  <select name="{{ widget.name }}">
    {% for option in duration_options %}
      <option value="{{ option.0 }}" {% if widget.value == option.0 %}selected{% endif %}>{{ option.1 }}</option>
    {% endfor %}
  </select>
  <span><button type="button" data-value="60">1h</button></span>
  <span><button type="button" data-value="90">1h30</button></span>
  <span><button type="button" data-value="120">2h</button></span>
  <span><button type="button" data-value="240">4h</button></span>
</span>
<script>
  $('.duration button').on('click', function() {
    $('select[name={{ widget.name }}]').val($(this).data('value')).trigger('change');
  });
  var $label = $('label[for=id_{{ widget.name }}]');
  var $endtime = $('<span class="endtime">XXX</span>');
  $endtime.appendTo($label.parent());
  var $start_time = $('#id_start_datetime_1');
  function format_00(val) {
    if (val < 10) return '0' + val;
    return val;
  }
  function update_endtime() {
    var start = $start_time.val().split(':')[0] * 60 + $start_time.val().split(':')[1] * 1;
    var duration = $('select[name={{ widget.name }}]').val() * 1;
    var end_time = start + duration;
    if (end_time >= 24 * 60) end_time -= 24 * 60;
    var end_str_time = parseInt(end_time / 60) + ':' + format_00(end_time % 60);
    $endtime.text('(→ ' + end_str_time + ')');
  }
  $('select[name={{ widget.name }}]').on('change', update_endtime).trigger('change');
  $start_time.on('change', update_endtime);
</script>

agendas/templates/agendas/splitdatetime.html
<span class="datetime">
  {% with widget=widget.subwidgets.0 %}
    <input type="date" name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value }}"{% endif %}{% include "django/forms/widgets/attrs.html" %} />
  {% endwith %}
  {% with widget=widget.subwidgets.1 %}
    <select name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %}>
      {% for option in time_options %}
        <option value="{{ option }}" {% if widget.value == option %}selected{% endif %}>{{ option }}</option>
      {% endfor %}
    </select>
  {% endwith %}
</span>

agendas/templates/agendas/studio_preferences.html
{% extends "base.html" %}
{% load i18n publik %}

{% block gadjo-js %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/panik-agendas.js"></script>
{% endblock %}

{% block css %}
  {{ block.super }}
  <link href="{{ STATIC_URL }}css/panik-agendas.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block appbar %}
  <h2>Préférences de studio</h2>
{% endblock %}

{% block content %}

  <div class="section">
    <div>
      <form action="" method="POST">
        {% csrf_token %}
        <table class="main studio-preferences">
          {% for emission in emissions %}
            <tr>
              <th>{{ emission }}</th>
              <td><label><input type="radio" name="emission-{{ emission.id }}" value="studio-1"
                                {% for pref in emission.emissionagendapreference_set.all %} {% if pref.agenda.slug == 'studio-1' %}checked{% endif %}{% endfor %}
                ><span>Studio 1</span></label></td>
              <td><label><input type="radio" name="emission-{{ emission.id }}" value="studio-2"
                                {% for pref in emission.emissionagendapreference_set.all %} {% if pref.agenda.slug == 'studio-2' %}checked{% endif %}{% endfor %}
                ><span>Studio 2</span></label></td>
              <td><label class="remove-prefs"><input type="radio" name="emission-{{ emission.id }}" value="none"
                ><span>×</span></label></td>
              <td class="around-time">
                {% with pre_time=emission.emissionagendapreference_set.all.0.pre_time %}
                  <select name="emission-{{ emission.id }}-pre-time"
                          class="pre-time" data-previous-value="{% firstof pre_time '0' %}">
                    <option value="0">—</option>
                    <option value="30" {% if pre_time == 30 %}selected{% endif %}>+ 30 minutes avant</option>
                    {% if pre_time and pre_time != 30 %}
                      <option value="{{ pre_time }}" selected>+ {{ pre_time }} minutes avant</option>
                    {% endif %}
                    <option value="other">Autre</option>
                  </select>
                {% endwith %}
                {% with post_time=emission.emissionagendapreference_set.all.0.post_time %}
                  <select name="emission-{{ emission.id }}-post-time"
                          class="post-time" data-previous-value="{% firstof post_time '0' %}">
                    <option value="0">—</option>
                    <option value="30" {% if post_time == 30 %}selected{% endif %}>+ 30 minutes après</option>
                    {% if post_time and post_time != 30 %}
                      {% if post_time < 0 %}
                        <option value="{{ post_time }}" selected>{{ post_time|abs }} minutes avant la fin</option>
                      {% else %}
                        <option value="{{ post_time }}" selected>+ {{ post_time }} minutes après</option>
                      {% endif %}
                    {% endif %}
                    <option value="other">Autre</option>
                  </select>
                {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </table>
        <div class="button">
          <button>Enregistrer</button>
        </div>
      </form>
    </div>
  </div>

  <dialog id="time-dlg">
    <form method="dialog">
      <p>
        <label>{% trans "Minutes before airtime:" %}</label>
        <input type="numeric"></input>
        <div class="buttons">
          <button value="cancel" class="cancel-button" formmethod="dialog">{% trans "Cancel" %}</button>
          <button value="default" class="submit-button">{% trans "Submit" %}</button>
        </div>
      </form>
    </dialog>

    <script>
      $('.around-time select').on('change', function() {
        var $select = $(this);
        if ($select.val() == 'other') {
          if ($select.is('.pre-time')) {
            $('#time-dlg label').text('{% trans "Minutes before airtime:" %}');
          } else {
            $('#time-dlg label').text('{% trans "Minutes after airtime:" %}');
          }
          $('#time-dlg input').val($select.data('previousValue'));
          $('#time-dlg button.submit-button').val($select.data('previousValue'));
          $('#time-dlg button.submit-button').off('click').on('click', function(e) {
            e.preventDefault();
            $('#time-dlg')[0].close($('#time-dlg input').val());
          });
          $('#time-dlg').off('close').on('close', function(e) {
            var time_dlg = $('#time-dlg')[0];
            if (time_dlg.returnValue === 'cancel') {
              $select.val($select.data('previousValue'));
            } else {
              var return_value = time_dlg.returnValue || ($select.data('previousValue'));
              if ($select.find('option[value="' + return_value + '"]').length === 0) {
                $('<option value="' + return_value + '">' + return_value + '</option>').appendTo($select);
              }
              $select.val(return_value);
              $select.data('previousValue', $select.val());
            }
          });
          $('#time-dlg')[0].showModal();
        } else {
          $select.data('previousValue', $select.val());
        }
      });
    </script>

{% endblock %}